apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv
  labels:
    app: mysql
spec:
  storageClassName: “manual”
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: Enterip-address
    # Exported path of your NFS server
    path: "/test"
