apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv2
  labels:
    app: mysql2
spec:
  storageClassName: "manual"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: Enterip-address
    # Exported path of your NFS server
    path: "/test2"